-- =========================================================================
-- Ghoomo Adaptive Learning Navigation Engine
-- Seed Data: EMPTY
-- =========================================================================
-- No production seed data.
-- Test fixtures are in src/lib/engine/__tests__/
-- The production app operates exclusively on real user-generated data
-- via authenticated Supabase sessions.
-- =========================================================================
