// ============================================================================
// Curated Sample Reels Catalog for Testing & Demonstration
// Covers every archetype defined in the Engineering Specification
// ============================================================================

import { TravelEvidence } from '../types/travelVideoPipeline';

export interface SampleReel {
  id: string;
  title: string;
  tagline: string;
  url: string;
  category: string;
  archetype:
    | 'explicit_itinerary'
    | 'destination_listicle'
    | 'seasonal_recommendation'
    | 'yearly_recommendation'
    | 'music_only_montage'
    | 'motivational_voiceover'
    | 'text_only_reel';
  thumbnailUrl: string;
  durationSeconds: number;
  mockEvidence: TravelEvidence;
}

export const SAMPLE_REELS_CATALOG: SampleReel[] = [
  {
    id: 'sample-bali-5day',
    title: 'My 5-Day Bali Tropical Itinerary',
    tagline: 'Explicit 5-day Bali trip with Uluwatu, Ubud, and Nusa Penida',
    url: 'https://www.instagram.com/reel/C_bali5day_sample/',
    category: 'Complete Itinerary',
    archetype: 'explicit_itinerary',
    thumbnailUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80',
    durationSeconds: 48,
    mockEvidence: {
      is_travel_video: true,
      travel_confidence: 0.98,
      video_type: 'ITINERARY',
      temporal_context: {
        month: 'September',
        season: 'Dry season',
        year: 2026,
        relative_expression: null,
      },
      destination_candidates: [
        {
          name: 'Bali, Indonesia',
          confidence: 0.98,
          country: 'Indonesia',
          evidence: [
            { type: 'text', description: 'Title overlay "5 Days in Bali"', timestamp: '00:02', confidence: 0.99 },
            { type: 'speech', description: 'Speaker explicitly introduces 5-day Bali trip', timestamp: '00:04', confidence: 0.97 },
            { type: 'landmark', description: 'Uluwatu cliff and temple visually visible', timestamp: '00:12', confidence: 0.95 },
          ],
        },
      ],
      primary_destination: 'Bali, Indonesia',
      places: [
        {
          name: 'Uluwatu Temple',
          canonicalName: 'Pura Luhur Uluwatu',
          type: 'temple',
          source: 'multiple',
          provenance: 'creator_multiple',
          confidence: 0.96,
          timestamp: '00:10',
          lat: -8.8291,
          lng: 115.0849,
          city: 'South Kuta',
          state: 'Bali',
          country: 'Indonesia',
          notes: 'Clifftop sunset views and historic sea temple',
          estimatedVisitMinutes: 120,
        },
        {
          name: 'Tegallalang Rice Terraces',
          canonicalName: 'Tegallalang Rice Terraces',
          type: 'nature',
          source: 'visual',
          provenance: 'creator_visual',
          confidence: 0.94,
          timestamp: '00:20',
          lat: -8.4343,
          lng: 115.2796,
          city: 'Ubud',
          state: 'Bali',
          country: 'Indonesia',
          notes: 'Lush green stepped paddy fields and swings',
          estimatedVisitMinutes: 90,
        },
        {
          name: 'Sacred Monkey Forest Sanctuary',
          canonicalName: 'Ubud Monkey Forest',
          type: 'nature',
          source: 'speech',
          provenance: 'creator_speech',
          confidence: 0.91,
          timestamp: '00:28',
          lat: -8.5189,
          lng: 115.2584,
          city: 'Ubud',
          state: 'Bali',
          country: 'Indonesia',
          notes: 'Dense jungle sanctuary with resident macaques',
          estimatedVisitMinutes: 90,
        },
        {
          name: 'Kelingking Beach',
          canonicalName: 'Kelingking T-Rex Beach',
          type: 'beach',
          source: 'visual',
          provenance: 'creator_visual',
          confidence: 0.95,
          timestamp: '00:36',
          lat: -8.7508,
          lng: 115.4746,
          city: 'Nusa Penida',
          state: 'Bali',
          country: 'Indonesia',
          notes: 'Iconic T-Rex shaped cliff and turquoise lagoon',
          estimatedVisitMinutes: 150,
        },
        {
          name: 'Seminyak Beach Club',
          canonicalName: 'Seminyak Beach',
          type: 'lifestyle',
          source: 'text',
          provenance: 'creator_text',
          confidence: 0.88,
          timestamp: '00:44',
          lat: -8.6896,
          lng: 115.1539,
          city: 'Seminyak',
          state: 'Bali',
          country: 'Indonesia',
          notes: 'Vibrant sunset lounge and beach relaxation',
          estimatedVisitMinutes: 120,
        },
      ],
      activities: [
        { name: 'Sunset watching at Uluwatu', confidence: 0.95, source: 'visual', timestamp: '00:15' },
        { name: 'Rice terrace trek', confidence: 0.92, source: 'visual', timestamp: '00:24' },
        { name: 'Speedboat to Nusa Penida', confidence: 0.88, source: 'speech', timestamp: '00:34' },
      ],
      duration: {
        days: 5,
        explicit: true,
        notes: 'Creator states "Here is my ultimate 5-day Bali itinerary"',
      },
      creator_recommendations: [
        'Rent a scooter or hire a private driver in Ubud',
        'Head to Uluwatu by 4:30 PM to catch the Kecak dance',
        'Book Nusa Penida fast boat one day in advance',
      ],
      speech: {
        available: true,
        travel_relevance: 0.92,
        summary: 'Direct day-by-day travel breakdown with specific venue advice',
      },
      evidence: [
        { type: 'text', description: 'Screen title: 5 Days in Bali', timestamp: '00:02', confidence: 0.99 },
        { type: 'landmark', description: 'Uluwatu Temple sea cliff', timestamp: '00:12', confidence: 0.95 },
      ],
    },
  },
  {
    id: 'sample-japan-top10',
    title: 'Top 10 Places in Japan You Must Visit',
    tagline: 'Listicle of Tokyo, Kyoto, Nara, and Osaka highlights without set days',
    url: 'https://www.youtube.com/shorts/japan_top10_places',
    category: 'Destination Listicle',
    archetype: 'destination_listicle',
    thumbnailUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
    durationSeconds: 58,
    mockEvidence: {
      is_travel_video: true,
      travel_confidence: 0.97,
      video_type: 'DESTINATION_GUIDE',
      temporal_context: {
        month: null,
        season: null,
        year: null,
        relative_expression: null,
      },
      destination_candidates: [
        {
          name: 'Japan',
          confidence: 0.97,
          country: 'Japan',
          evidence: [
            { type: 'text', description: 'On-screen title "Top 10 Places in Japan"', timestamp: '00:03', confidence: 0.98 },
            { type: 'landmark', description: 'Fushimi Inari torii gates', timestamp: '00:14', confidence: 0.96 },
          ],
        },
      ],
      primary_destination: 'Japan (Tokyo & Kyoto Corridor)',
      places: [
        {
          name: 'Senso-ji Temple',
          canonicalName: 'Sensō-ji',
          type: 'temple',
          source: 'visual',
          provenance: 'creator_visual',
          confidence: 0.95,
          timestamp: '00:08',
          lat: 35.7148,
          lng: 139.7967,
          city: 'Tokyo',
          state: 'Kanto',
          country: 'Japan',
          notes: 'Ancient Buddhist temple in Asakusa with Nakamise shopping street',
          estimatedVisitMinutes: 90,
        },
        {
          name: 'Shibuya Crossing',
          canonicalName: 'Shibuya Scramble Crossing',
          type: 'landmark',
          source: 'visual',
          provenance: 'creator_visual',
          confidence: 0.96,
          timestamp: '00:15',
          lat: 35.6595,
          lng: 139.7005,
          city: 'Tokyo',
          state: 'Kanto',
          country: 'Japan',
          notes: 'World-famous pedestrian crossing illuminated by neon signs',
          estimatedVisitMinutes: 60,
        },
        {
          name: 'Fushimi Inari Taisha',
          canonicalName: 'Fushimi Inari-taisha',
          type: 'shrine',
          source: 'multiple',
          provenance: 'creator_multiple',
          confidence: 0.98,
          timestamp: '00:23',
          lat: 34.9671,
          lng: 135.7727,
          city: 'Kyoto',
          state: 'Kansai',
          country: 'Japan',
          notes: 'Thousands of vibrant vermilion torii gates winding up Mount Inari',
          estimatedVisitMinutes: 120,
        },
        {
          name: 'Kinkaku-ji (Golden Pavilion)',
          canonicalName: 'Kinkaku-ji',
          type: 'temple',
          source: 'visual',
          provenance: 'creator_visual',
          confidence: 0.94,
          timestamp: '00:32',
          lat: 35.0394,
          lng: 135.7292,
          city: 'Kyoto',
          state: 'Kansai',
          country: 'Japan',
          notes: 'Zen temple whose top two floors are completely covered in gold leaf',
          estimatedVisitMinutes: 90,
        },
        {
          name: 'Nara Deer Park',
          canonicalName: 'Nara Park',
          type: 'park',
          source: 'speech',
          provenance: 'creator_speech',
          confidence: 0.92,
          timestamp: '00:41',
          lat: 34.6851,
          lng: 135.843,
          city: 'Nara',
          state: 'Kansai',
          country: 'Japan',
          notes: 'Peaceful park where hundreds of freely roaming sika deer bow for crackers',
          estimatedVisitMinutes: 100,
        },
        {
          name: 'Dotonbori Street',
          canonicalName: 'Dōtonbori',
          type: 'food_street',
          source: 'text',
          provenance: 'creator_text',
          confidence: 0.91,
          timestamp: '00:50',
          lat: 34.6687,
          lng: 135.5013,
          city: 'Osaka',
          state: 'Kansai',
          country: 'Japan',
          notes: 'Lively food district renowned for takoyaki, okonomiyaki, and neon signs',
          estimatedVisitMinutes: 120,
        },
      ],
      activities: [
        { name: 'Feeding deer in Nara', confidence: 0.95, source: 'visual', timestamp: '00:43' },
        { name: 'Street food tasting in Dotonbori', confidence: 0.9, source: 'text', timestamp: '00:52' },
      ],
      duration: {
        days: null,
        explicit: false,
        notes: 'Listicle format: Optimal duration must be calculated by the deterministic DurationEngine',
      },
      creator_recommendations: [
        'Get a 7-day JR Pass or regional Kansai pass for bullet trains',
        'Visit Fushimi Inari at dawn to avoid the dense tour crowds',
      ],
      speech: {
        available: true,
        travel_relevance: 0.85,
        summary: 'Narrator presents top sightseeing highlights across Tokyo, Kyoto, and Osaka',
      },
      evidence: [
        { type: 'text', description: 'Top 10 list ranking overlay', timestamp: '00:03', confidence: 0.98 },
        { type: 'landmark', description: 'Kinkaku-ji temple reflection', timestamp: '00:32', confidence: 0.94 },
      ],
    },
  },
  {
    id: 'sample-september-recs',
    title: 'Best Places to Visit in September',
    tagline: 'Seasonal recommendation video with multiple candidate destinations',
    url: 'https://www.instagram.com/reel/C_september_best_places/',
    category: 'Seasonal Recommendations',
    archetype: 'seasonal_recommendation',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    durationSeconds: 42,
    mockEvidence: {
      is_travel_video: true,
      travel_confidence: 0.96,
      video_type: 'SEASONAL_RECOMMENDATION',
      temporal_context: {
        month: 'September',
        season: 'Late Summer / Early Autumn',
        year: 2026,
        relative_expression: 'in September',
        resolved_month: 9,
        resolved_year: 2026,
      },
      destination_candidates: [
        {
          name: 'Santorini, Greece',
          confidence: 0.94,
          country: 'Greece',
          region: 'Cyclades',
          evidence: [
            { type: 'text', description: 'On-screen caption "1. Santorini, Greece - Perfect warm water, zero summer crowds"', timestamp: '00:05', confidence: 0.96 },
            { type: 'landmark', description: 'Oia blue dome churches and Aegean caldera', timestamp: '00:08', confidence: 0.95 },
          ],
        },
        {
          name: 'Kyoto, Japan',
          confidence: 0.92,
          country: 'Japan',
          region: 'Kansai',
          evidence: [
            { type: 'text', description: 'On-screen caption "2. Kyoto, Japan - Early autumn foliage and temple gardens"', timestamp: '00:18', confidence: 0.93 },
            { type: 'landmark', description: 'Arashiyama bamboo grove and traditional teahouses', timestamp: '00:22', confidence: 0.91 },
          ],
        },
        {
          name: 'Bali, Indonesia',
          confidence: 0.91,
          country: 'Indonesia',
          region: 'Southeast Asia',
          evidence: [
            { type: 'text', description: 'On-screen caption "3. Bali, Indonesia - Clear skies and perfect surf waves"', timestamp: '00:30', confidence: 0.92 },
            { type: 'landmark', description: 'Tanah Lot ocean temple', timestamp: '00:34', confidence: 0.89 },
          ],
        },
      ],
      primary_destination: 'Santorini, Greece', // Primary candidate default, but UI allows selection
      places: [
        {
          name: 'Oia Village & Castle',
          canonicalName: 'Oia, Santorini',
          type: 'village',
          source: 'visual',
          provenance: 'creator_visual',
          confidence: 0.96,
          timestamp: '00:09',
          lat: 36.4618,
          lng: 25.3753,
          city: 'Oia',
          state: 'South Aegean',
          country: 'Greece',
          notes: 'Whitewashed houses, blue domes, and world-famous caldera sunsets',
          estimatedVisitMinutes: 150,
        },
        {
          name: 'Fira to Oia Caldera Trail',
          canonicalName: 'Fira-Oia Hike',
          type: 'trail',
          source: 'speech',
          provenance: 'creator_speech',
          confidence: 0.9,
          timestamp: '00:12',
          lat: 36.43,
          lng: 25.42,
          city: 'Fira',
          state: 'South Aegean',
          country: 'Greece',
          notes: 'Scenic 10km cliffside hiking route overlooking the submerged volcano',
          estimatedVisitMinutes: 180,
        },
        {
          name: 'Red Beach (Kokkini Paralia)',
          canonicalName: 'Red Beach',
          type: 'beach',
          source: 'visual',
          provenance: 'creator_visual',
          confidence: 0.92,
          timestamp: '00:15',
          lat: 36.3486,
          lng: 25.3948,
          city: 'Akrotiri',
          state: 'South Aegean',
          country: 'Greece',
          notes: 'Dramatic crimson volcanic cliffs and warm Aegean swimming cove',
          estimatedVisitMinutes: 120,
        },
      ],
      activities: [
        { name: 'Sunset watching in Oia', confidence: 0.96, source: 'visual', timestamp: '00:10' },
        { name: 'Sailing caldera catamaran cruise', confidence: 0.88, source: 'speech', timestamp: '00:14' },
      ],
      duration: {
        days: 4,
        explicit: false,
        notes: 'Recommended 4-day stay for the selected candidate',
      },
      creator_recommendations: [
        'September has 28°C sea temperatures and hotel rates drop by 35%',
        'Rent a small car or ATV to explore Akrotiri ruins and southern coves',
      ],
      speech: {
        available: true,
        travel_relevance: 0.88,
        summary: 'Narrator explains why September is the best shoulder season across these 3 regions',
      },
      evidence: [
        { type: 'text', description: 'September recommendation title', timestamp: '00:02', confidence: 0.97 },
      ],
    },
  },
  {
    id: 'sample-swiss-music-only',
    title: 'Swiss Alps Pure Scenery Montage (Music Only)',
    tagline: 'Zero spoken voice or narration — pure visual landmark & scenic video understanding',
    url: 'https://www.instagram.com/reel/C_swiss_alps_music_only/',
    category: 'Music-Only Montage',
    archetype: 'music_only_montage',
    thumbnailUrl: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=800&q=80',
    durationSeconds: 35,
    mockEvidence: {
      is_travel_video: true,
      travel_confidence: 0.95,
      video_type: 'TRAVEL_MONTAGE',
      temporal_context: {
        month: 'June',
        season: 'Summer Alpine',
        year: 2026,
        relative_expression: null,
      },
      destination_candidates: [
        {
          name: 'Jungfrau Region, Switzerland',
          confidence: 0.95,
          country: 'Switzerland',
          evidence: [
            { type: 'landmark', description: 'Lauterbrunnen valley 72 waterfalls and Staubbach Falls', timestamp: '00:06', confidence: 0.98 },
            { type: 'landmark', description: 'Grindelwald First cliff walk and Eiger North Face', timestamp: '00:18', confidence: 0.95 },
            { type: 'text', description: 'Train carriage exterior logo "Jungfraubahn"', timestamp: '00:26', confidence: 0.96 },
          ],
        },
      ],
      primary_destination: 'Lauterbrunnen & Jungfrau Region, Switzerland',
      places: [
        {
          name: 'Staubbach Waterfall',
          canonicalName: 'Staubbach Falls',
          type: 'waterfall',
          source: 'visual',
          provenance: 'creator_visual',
          confidence: 0.97,
          timestamp: '00:07',
          lat: 46.594,
          lng: 7.908,
          city: 'Lauterbrunnen',
          state: 'Bern',
          country: 'Switzerland',
          notes: 'Nearly 300-meter plunging waterfall behind traditional wooden alpine chalets',
          estimatedVisitMinutes: 60,
        },
        {
          name: 'Grindelwald First Cliff Walk',
          canonicalName: 'First Cliff Walk by Tissot',
          type: 'viewpoint',
          source: 'visual',
          provenance: 'creator_visual',
          confidence: 0.95,
          timestamp: '00:19',
          lat: 46.6586,
          lng: 8.0531,
          city: 'Grindelwald',
          state: 'Bern',
          country: 'Switzerland',
          notes: 'Suspended walkway along the rock face with jaw-dropping Eiger vistas',
          estimatedVisitMinutes: 90,
        },
        {
          name: 'Lake Bachalpsee',
          canonicalName: 'Bachalpsee',
          type: 'lake',
          source: 'visual',
          provenance: 'creator_visual',
          confidence: 0.94,
          timestamp: '00:27',
          lat: 46.6685,
          lng: 8.0219,
          city: 'Grindelwald',
          state: 'Bern',
          country: 'Switzerland',
          notes: 'Mirror-like alpine lake reflecting snow-capped peaks and wildflowers',
          estimatedVisitMinutes: 120,
        },
        {
          name: 'Mürren Alpine Village',
          canonicalName: 'Mürren',
          type: 'village',
          source: 'visual',
          provenance: 'creator_visual',
          confidence: 0.91,
          timestamp: '00:32',
          lat: 46.5593,
          lng: 7.8931,
          city: 'Mürren',
          state: 'Bern',
          country: 'Switzerland',
          notes: 'Car-free mountain hamlet perched high on cliffs opposite Jungfrau massif',
          estimatedVisitMinutes: 90,
        },
      ],
      activities: [
        { name: 'Panoramic Alpine hiking', confidence: 0.95, source: 'visual', timestamp: '00:15' },
        { name: 'Cogwheel train journey', confidence: 0.93, source: 'visual', timestamp: '00:28' },
      ],
      duration: {
        days: null,
        explicit: false,
        notes: 'Determined by geographic clustering and daily capacity engine (3-4 days ideal)',
      },
      creator_recommendations: [
        'Take the Berner Oberland Pass for unlimited cable cars and trains',
        'Early morning hike from First to Bachalpsee offers glassy reflections',
      ],
      speech: {
        available: false,
        travel_relevance: 0.0,
        summary: 'No spoken dialogue or voiceover detected. Background acoustic music only.',
      },
      evidence: [
        { type: 'audio', description: 'Acoustic background music without lyrics', timestamp: '00:01', confidence: 0.99 },
        { type: 'landmark', description: 'Staubbach Falls in Lauterbrunnen', timestamp: '00:06', confidence: 0.98 },
        { type: 'text', description: 'Yellow Swiss hiking trail signs (Wanderweg)', timestamp: '00:22', confidence: 0.92 },
      ],
    },
  },
  {
    id: 'sample-manali-motivational',
    title: 'Himalayan Escape (Motivational Audio + Drone Travel Footage)',
    tagline: 'Generic motivational monologue filtered out; visual landmarks identify Solang & Rohtang',
    url: 'https://www.instagram.com/reel/C_manali_spiti_motivational/',
    category: 'Motivational Travel',
    archetype: 'motivational_voiceover',
    thumbnailUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80',
    durationSeconds: 45,
    mockEvidence: {
      is_travel_video: true,
      travel_confidence: 0.94,
      video_type: 'MOTIVATIONAL_TRAVEL',
      temporal_context: {
        month: 'October',
        season: 'Autumn Himalayan',
        year: 2026,
        relative_expression: null,
      },
      destination_candidates: [
        {
          name: 'Manali & Rohtang Pass, Himachal Pradesh',
          confidence: 0.94,
          country: 'India',
          region: 'Himachal Pradesh',
          evidence: [
            { type: 'landmark', description: 'Rohtang Pass high-altitude gateway and snowfields', timestamp: '00:14', confidence: 0.96 },
            { type: 'landmark', description: 'Solang Valley paragliding arena', timestamp: '00:26', confidence: 0.92 },
            { type: 'text', description: 'Signboard "Atal Tunnel South Portal"', timestamp: '00:38', confidence: 0.97 },
          ],
        },
      ],
      primary_destination: 'Manali, Himachal Pradesh, India',
      places: [
        {
          name: 'Hadimba Devi Temple',
          canonicalName: 'Hidimba Devi Temple',
          type: 'temple',
          source: 'visual',
          provenance: 'creator_visual',
          confidence: 0.94,
          timestamp: '00:08',
          lat: 32.2483,
          lng: 77.1812,
          city: 'Manali',
          state: 'Himachal Pradesh',
          country: 'India',
          notes: 'Pagoda-style wooden sanctuary surrounded by cedar deodar forests',
          estimatedVisitMinutes: 75,
        },
        {
          name: 'Solang Valley',
          canonicalName: 'Solang Valley',
          type: 'adventure',
          source: 'visual',
          provenance: 'creator_visual',
          confidence: 0.93,
          timestamp: '00:22',
          lat: 32.3166,
          lng: 77.1575,
          city: 'Manali',
          state: 'Himachal Pradesh',
          country: 'India',
          notes: 'Hub for paragliding, ATV rides, and panoramic snow-peak backdrops',
          estimatedVisitMinutes: 120,
        },
        {
          name: 'Atal Tunnel South Portal',
          canonicalName: 'Atal Tunnel',
          type: 'landmark',
          source: 'text',
          provenance: 'creator_text',
          confidence: 0.97,
          timestamp: '00:37',
          lat: 32.3619,
          lng: 77.1352,
          city: 'Dhundi',
          state: 'Himachal Pradesh',
          country: 'India',
          notes: 'Engineering marvel connecting Kullu Valley to Lahaul and Spiti',
          estimatedVisitMinutes: 45,
        },
        {
          name: 'Rohtang Pass',
          canonicalName: 'Rohtang La',
          type: 'mountain_pass',
          source: 'visual',
          provenance: 'creator_visual',
          confidence: 0.95,
          timestamp: '00:41',
          lat: 32.3716,
          lng: 77.2466,
          city: 'Manali',
          state: 'Himachal Pradesh',
          country: 'India',
          notes: 'Breathtaking 3,978m mountain pass with glaciers and Himalayan peaks',
          estimatedVisitMinutes: 120,
        },
      ],
      activities: [
        { name: 'Paragliding over Solang Valley', confidence: 0.95, source: 'visual', timestamp: '00:24' },
        { name: 'Driving through Atal Tunnel into Lahaul', confidence: 0.94, source: 'text', timestamp: '00:38' },
      ],
      duration: {
        days: 3,
        explicit: false,
        notes: 'Optimal 3-day weekend circuit calculated for Manali, Solang, and Rohtang',
      },
      creator_recommendations: [
        'Secure Rohtang Pass entry permit 48 hours in advance',
        'Visit Hadimba temple early morning for quiet photography among deodars',
      ],
      speech: {
        available: true,
        travel_relevance: 0.08,
        summary: 'Speaker delivers general motivational speech about leaving your comfort zone and chasing dreams. Zero destination names spoken.',
      },
      evidence: [
        { type: 'speech', description: 'Motivational speech detected ("Life begins at the end of your comfort zone...") - low travel relevance 0.08', timestamp: '00:04', confidence: 0.99 },
        { type: 'landmark', description: 'Deodar forest and Hadimba temple architecture', timestamp: '00:08', confidence: 0.94 },
        { type: 'text', description: 'Highway marker indicating Manali-Leh Highway NH-3', timestamp: '00:35', confidence: 0.95 },
      ],
    },
  },
  {
    id: 'sample-paris-text-only',
    title: 'Paris Hidden Secrets (Text Overlays & Subtitles Only)',
    tagline: 'Silent Reel where creator relies entirely on on-screen text coordinates and guides',
    url: 'https://www.instagram.com/reel/C_paris_hidden_text_only/',
    category: 'Text-Only Guide',
    archetype: 'text_only_reel',
    thumbnailUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
    durationSeconds: 38,
    mockEvidence: {
      is_travel_video: true,
      travel_confidence: 0.98,
      video_type: 'TRAVEL_TIPS',
      temporal_context: {
        month: 'May',
        season: 'Spring',
        year: 2026,
        relative_expression: null,
      },
      destination_candidates: [
        {
          name: 'Paris, France',
          confidence: 0.99,
          country: 'France',
          evidence: [
            { type: 'text', description: 'Headline text "Stop going only to Eiffel Tower: 4 hidden Paris spots"', timestamp: '00:02', confidence: 0.99 },
            { type: 'text', description: 'Address overlay "Rue Cremieux, 75012 Paris"', timestamp: '00:11', confidence: 0.98 },
          ],
        },
      ],
      primary_destination: 'Paris, France',
      places: [
        {
          name: 'Rue Crémieux',
          canonicalName: 'Rue Crémieux',
          type: 'street',
          source: 'text',
          provenance: 'creator_text',
          confidence: 0.98,
          timestamp: '00:10',
          lat: 48.8469,
          lng: 2.3707,
          city: 'Paris',
          state: 'Île-de-France',
          country: 'France',
          notes: 'Cobblestone pedestrian street famous for pastel-painted townhouse facades',
          estimatedVisitMinutes: 45,
        },
        {
          name: 'Sainte-Chapelle',
          canonicalName: 'Sainte-Chapelle',
          type: 'monument',
          source: 'text',
          provenance: 'creator_text',
          confidence: 0.96,
          timestamp: '00:18',
          lat: 48.8554,
          lng: 2.345,
          city: 'Paris',
          state: 'Île-de-France',
          country: 'France',
          notes: 'Gothic royal chapel with 1,113 mesmerizing 13th-century stained glass panes',
          estimatedVisitMinutes: 75,
        },
        {
          name: 'Palais-Royal Colonnes de Buren',
          canonicalName: 'Colonnes de Buren, Palais-Royal',
          type: 'art',
          source: 'visual',
          provenance: 'creator_visual',
          confidence: 0.94,
          timestamp: '00:26',
          lat: 48.8637,
          lng: 2.3371,
          city: 'Paris',
          state: 'Île-de-France',
          country: 'France',
          notes: 'Striped black-and-white marble columns in historic palace courtyard',
          estimatedVisitMinutes: 60,
        },
        {
          name: 'Montmartre Secret Vineyard (Clos Montmartre)',
          canonicalName: 'Vignes du Clos Montmartre',
          type: 'vineyard',
          source: 'text',
          provenance: 'creator_text',
          confidence: 0.92,
          timestamp: '00:33',
          lat: 48.8878,
          lng: 2.3402,
          city: 'Paris',
          state: 'Île-de-France',
          country: 'France',
          notes: 'Historic hillside vineyard tucked directly behind Sacré-Cœur basilica',
          estimatedVisitMinutes: 60,
        },
      ],
      activities: [
        { name: 'Stained glass viewing in Île de la Cité', confidence: 0.95, source: 'text', timestamp: '00:19' },
        { name: 'Montmartre backstreet walking tour', confidence: 0.92, source: 'text', timestamp: '00:34' },
      ],
      duration: {
        days: 2,
        explicit: false,
        notes: '2-day Paris boutique exploration route',
      },
      creator_recommendations: [
        'Book Sainte-Chapelle morning slot for the most luminous sunlight through glass',
        'Respect quiet residential rules on Rue Crémieux',
      ],
      speech: {
        available: false,
        travel_relevance: 0.0,
        summary: 'No speech. 100% information conveyed via on-screen subtitles and location tags.',
      },
      evidence: [
        { type: 'text', description: 'Detailed on-screen address coordinates and arrondissement numbers', timestamp: '00:03', confidence: 0.99 },
      ],
    },
  },
];

export function findSampleReel(query: string): SampleReel | undefined {
  const q = query.trim().toLowerCase();
  return SAMPLE_REELS_CATALOG.find(
    (s) =>
      s.id.toLowerCase() === q ||
      s.url.toLowerCase() === q ||
      s.title.toLowerCase().includes(q) ||
      s.archetype.toLowerCase().includes(q)
  );
}
