import { PlatformType, Place, TripSource } from '@/lib/types/ghoomo';

export interface SampleReelBundle {
  id: string;
  url: string;
  platform: PlatformType;
  title: string;
  author: string;
  thumbnailUrl: string;
  destination: string;
  places: Omit<Place, 'id' | 'tripId' | 'sourceId' | 'createdAt'>[];
}

export const SAMPLE_VIRAL_REELS: SampleReelBundle[] = [
  {
    id: 'jaipur-hidden-gems',
    url: 'https://www.instagram.com/reel/C8JaipurSecretGems99/',
    platform: 'instagram',
    title: '7 Secret Aesthetic Spots in Jaipur Most Tourists Miss! 🏰✨',
    author: '@shutter_traveller_raj',
    thumbnailUrl: 'https://images.unsplash.com/photo-1603258849062-850f1f1d1f70?auto=format&fit=crop&w=800&q=80',
    destination: 'Jaipur, Rajasthan',
    places: [
      {
        name: 'Panna Meena Ka Kund',
        city: 'Jaipur',
        state: 'Rajasthan',
        lat: 26.9856,
        lng: 75.8507,
        category: 'heritage',
        confidence: 0.98,
        imageUrl: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=600&q=80',
        notes: '16th-century geometric stepwell. Best photos before 8:30 AM before security crowds.',
      },
      {
        name: 'Nahargarh Fort Sunset Point',
        city: 'Jaipur',
        state: 'Rajasthan',
        lat: 26.9373,
        lng: 75.8156,
        category: 'viewpoint',
        confidence: 0.95,
        imageUrl: 'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=600&q=80',
        notes: 'Padao open-air restaurant terrace over the pink city rim at golden hour.',
      },
      {
        name: 'Gaitore Ki Chhatriyan',
        city: 'Jaipur',
        state: 'Rajasthan',
        lat: 26.9452,
        lng: 75.8277,
        category: 'cenotaph',
        confidence: 0.91,
        imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=600&q=80',
        notes: 'Intricately carved white marble royal cenotaphs nestled in the valley base.',
      },
      {
        name: 'Jawahar Kala Kendra & Indian Coffee House',
        city: 'Jaipur',
        state: 'Rajasthan',
        lat: 26.8828,
        lng: 75.8078,
        category: 'cafe & arts',
        confidence: 0.88,
        imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=600&q=80',
        notes: 'Charles Correa architectural modernist cultural center with legendary cold coffee.',
      },
      {
        name: 'Caffix Tech Cafe & Barista',
        city: 'Jaipur',
        state: 'Rajasthan',
        lat: 26.9015,
        lng: 75.8035,
        category: 'cafe',
        confidence: 0.84,
        imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=600&q=80',
        notes: 'Custom selfie foam latte cafe featured in viral Rajasthan food vlogs.',
      },
    ],
  },
  {
    id: 'varanasi-spiritual-trail',
    url: 'https://www.youtube.com/shorts/KashiSunriseMagic2026',
    platform: 'youtube',
    title: 'Secret Sunrise & Heritage Ghats in Varanasi 🕉️🌅',
    author: '@banaras_diaries',
    thumbnailUrl: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80',
    destination: 'Varanasi, Uttar Pradesh',
    places: [
      {
        name: 'Assi Ghat Subah-e-Banaras',
        city: 'Varanasi',
        state: 'Uttar Pradesh',
        lat: 25.2917,
        lng: 83.0076,
        category: 'spiritual',
        confidence: 0.99,
        imageUrl: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=600&q=80',
        notes: 'Classical sitar, morning yagya, and boat rowers departing at 5:15 AM.',
      },
      {
        name: 'Chet Singh Fort Ghat',
        city: 'Varanasi',
        state: 'Uttar Pradesh',
        lat: 25.2974,
        lng: 83.0089,
        category: 'heritage',
        confidence: 0.92,
        imageUrl: 'https://images.unsplash.com/photo-1571536802807-30451e3955d8?auto=format&fit=crop&w=600&q=80',
        notes: 'Dramatic 18th-century fortified stone battlements directly touching the Ganga river.',
      },
      {
        name: 'Blue Lassi Shop',
        city: 'Varanasi',
        state: 'Uttar Pradesh',
        lat: 25.3115,
        lng: 83.0135,
        category: 'food',
        confidence: 0.96,
        imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
        notes: 'Hand-churned clay pot lassi topped with pomegranate, dry fruits, and rabri since 1925.',
      },
      {
        name: 'Manikarnika Viewpoint from Boat',
        city: 'Varanasi',
        state: 'Uttar Pradesh',
        lat: 25.3109,
        lng: 83.0152,
        category: 'cultural',
        confidence: 0.89,
        imageUrl: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=600&q=80',
        notes: 'Sacred timeless cremation ghat. Observe with quiet reverence from river boat.',
      },
    ],
  },
  {
    id: 'south-goa-cliff-cafes',
    url: 'https://www.tiktok.com/@goa_unexplored/video/73918237190',
    platform: 'tiktok',
    title: 'Unreal South Goa Cliff Trails & Hidden Blue Lagoons 🌊🌴',
    author: '@goa_unexplored',
    thumbnailUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
    destination: 'South Goa, Goa',
    places: [
      {
        name: 'Cabo de Rama Cape & Cliff View',
        city: 'Canacona',
        state: 'Goa',
        lat: 15.0883,
        lng: 73.9217,
        category: 'nature',
        confidence: 0.97,
        imageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=600&q=80',
        notes: 'Panoramic Arabian sea cliff with wild palm grooves and ancient fort ramparts.',
      },
      {
        name: 'Cola Beach Emerald Lagoon',
        city: 'Canacona',
        state: 'Goa',
        lat: 15.0567,
        lng: 73.9742,
        category: 'beach',
        confidence: 0.94,
        imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
        notes: 'Freshwater green lagoon meeting ocean waves. Kayaking under coconut canopies.',
      },
      {
        name: 'Butterfly Beach Secret Cove',
        city: 'Palolem',
        state: 'Goa',
        lat: 15.0189,
        lng: 74.0156,
        category: 'adventure',
        confidence: 0.91,
        imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
        notes: 'Semi-circular secluded bay reached by boat or a 30-min jungle trek from leopard valley.',
      },
      {
        name: 'Fishermans Wharf Riverside',
        city: 'Cavelossim',
        state: 'Goa',
        lat: 15.1764,
        lng: 73.9442,
        category: 'food',
        confidence: 0.88,
        imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80',
        notes: 'Authentic Goan prawn balchão & live fado music on the Sal river wooden jetty.',
      },
    ],
  },
  {
    id: 'manali-parvati-valley',
    url: 'https://thewanderingindian.com/blogs/parvati-valley-secret-hikes',
    platform: 'blog',
    title: 'Hidden Waterfalls & Bohemian Cafes in Parvati Valley 🏔️🌲',
    author: 'The Wandering Indian Blog',
    thumbnailUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80',
    destination: 'Kasol & Parvati Valley, Himachal',
    places: [
      {
        name: 'Chalal Pine Forest Trail',
        city: 'Kasol',
        state: 'Himachal Pradesh',
        lat: 32.0135,
        lng: 77.3195,
        category: 'trek',
        confidence: 0.96,
        imageUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=600&q=80',
        notes: 'Peaceful walk across Parvati river cable bridge into deodar cedar groves.',
      },
      {
        name: 'Tosh Glacier View Waterfall',
        city: 'Tosh',
        state: 'Himachal Pradesh',
        lat: 32.0197,
        lng: 77.4528,
        category: 'nature',
        confidence: 0.93,
        imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=600&q=80',
        notes: 'Steep cobbled trail behind wooden village leading to foaming Himalayan falls.',
      },
      {
        name: 'Manikarnika Natural Hot Springs',
        city: 'Manikaran',
        state: 'Himachal Pradesh',
        lat: 32.0289,
        lng: 77.3488,
        category: 'spiritual & wellness',
        confidence: 0.97,
        imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
        notes: 'Sulfur thermal mineral pools and continuous community langar food service.',
      },
    ],
  },
];
